name: Create crate dist
on:
  push:
    tags:
      - '*'
  workflow_call:
    inputs:
      directories:
        description: Directories with Cargo.toml files to process
        default: rust/lib-hwengine-future
        required: false
        type: string

jobs:
  create-dist:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install pycargoebuild
        shell: bash
        run: pip install pycargoebuild
      - name: Grab the license mapping
        shell: bash
        run: |
          wget https://raw.githubusercontent.com/gentoo/gentoo/refs/heads/master/metadata/license-mapping.conf
      - name: Generate cargo lock file
        shell: bash
        run: cd ${{ inputs.directories }} && cargo generate-lockfile
      - name: Cache fetched crates
        uses: actions/cache@v4
        with:
          path: /tmp/dist
          key: dist
      - name: Create a dist tarball
        shell: bash
        run: |
          pycargoebuild \
            --crate-tarball \
            --crate-tarball-path "hedgewars-@TAG@-crates.tar.xz" \
            --distdir /tmp/dist \
            --license-mapping license-mapping.conf \
            ${{ inputs.directories }}
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body:
          files: ${{ inputs.dist-filename }}
          tag_name: ${{ inputs.tag }}
          fail_on_unmatched_files: true
