name: Sync with upstream
on:
  schedule:
    - cron: "10 */6 * * *"
  push:

jobs:
  sync-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Update mirror
        uses: projg2/crate-dist-mirror-action@v2
        with:
          ssh-private-key: ${{ secrets.ssh_key }}
          directories: rust/lib-hwengine-future
          upstream-repo: https://github.com/hedgewars/hw.git
