name: Create snapshot
on:
  push:
    branches:
      - 'master'
    tags:
      - '*_pre*'

jobs:
  snapshot-tarball:
    runs-on: ubuntu-latest
    steps:
      - name: Create snapshot tarball
        uses: $/.github/actions/crate-dist
        with:
          directories: rust/lib-hwengine-future rust/hedgewars-server
          dist-filename: hedgewars-${{ github.ref_name }}-crates.tar.xz
